allowBuilds:
  '@clerk/shared': true
  '@parcel/watcher': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  utf-8-validate: true
