// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardOffersSortBy } from './CardOffersSortBy';

export type CardOffersParams = {
  set_code: string;
  collector_number: string;
  language_code: string;
  foil: boolean;
  sort_by: CardOffersSortBy;
  page: number;
  page_size: number;
};
