// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardOffer = { owner_username: string; quantity: number; selling_price: number | null };
