// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionEntry } from './CollectionEntry';
import type { PriceGuide } from './PriceGuide';

export type CollectionCard = {
  set_code: string;
  collector_number: string;
  language_code: string;
  foil: boolean;
  name: string;
  rarity_code: string;
  scryfall_id: string;
  the_gatherer_id: string | null;
  /**
   * Present only when the card is owned by the authenticated user.
   */
  collection_entry: CollectionEntry | null;
  /**
   * Username of the owner when the card belongs to another user (catalog listing).
   */
  owner_username: string | null;
  price_guide: PriceGuide | null;
};
