// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RarityCode } from './RarityCode';
import type { SortBy } from './SortBy';
import type { SortDir } from './SortDir';

export type CollectionParams = {
  page: number;
  page_size: number;
  sort_by: SortBy;
  sort_dir: SortDir;
  q?: string;
  /**
   * Rarity codes, repeated for multiple values (e.g. `?rarity=C&rarity=U`)
   */
  rarity: Array<RarityCode>;
  /**
   * Comma-separated set codes
   */
  sets?: string;
  /**
   * Minimum trend price in cents
   */
  price_min?: number;
  /**
   * Maximum trend price in cents
   */
  price_max?: number;
  /**
   * Restrict to cards owned by the authenticated user (default: false — full catalog)
   */
  owned: boolean;
};
