// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectionEntry = {
  quantity: number;
  purchase_price: number;
  /**
   * RFC 3339 timestamp
   */
  added_at: string;
};
