// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetInfo } from './SetInfo';

export type CollectionStats = {
  total_cards: number;
  unique_cards: number;
  price_trend_min: number | null;
  price_trend_max: number | null;
  sets: Array<SetInfo>;
};
