// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared by `/collection/price-history` and `/cards/{scryfall_id}/price-history`; both dates are
 * optional and defaulted by the use case (last 30 days when absent).
 */
export type PriceHistoryParams = {
  /**
   * ISO 8601 date string (YYYY-MM-DD)
   */
  start_date?: string;
  /**
   * ISO 8601 date string (YYYY-MM-DD)
   */
  end_date?: string;
};
