// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PriceGuide = { low: number | null; avg: number | null; trend: number | null };
