// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PriceHistoryEntry = {
  /**
   * ISO 8601 date string (YYYY-MM-DD)
   */
  date: string;
  low: number;
  trend: number;
  avg: number;
};
