// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceGuide } from './PriceGuide';

export type CollectionCard = {
  set_code: string;
  collector_number: string;
  language_code: string;
  foil: boolean;
  name: string;
  rarity_code: string;
  scryfall_id: string;
  quantity: number;
  purchase_price: number;
  price_guide: PriceGuide | null;
};
