// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionCard } from './CollectionCard';

export type PaginatedCollection = {
  items: Array<CollectionCard>;
  total: number;
  page: number;
  page_size: number;
};
